// Uzupełnić to i dodać tu także tablicę ze wszystkimi stolicami
const hoverEffectObj = {
    '01d' : `radial-gradient(rgba(80, 140, 200, 0.2), rgba(80, 140, 200, 0.2), rgba(200, 255, 255, 0.2), rgba(200, 255, 255, 0.5), rgba(200, 255, 255, 0.65))`,
    '04d' : `radial-gradient(#791a, #369b)`,
    '10d' : `radial-gradient(#4288, #51bc)`,
}

const capitalCities = [
    `Abu Dhabi`,	
    `Abuja`,	
    `Accra`,	
    `Addis Ababa`,
    `Algiers`,	
    `Amman`,
    `Amsterdam`,
    //`Andorra la Vella`,
    `Ankara`,
    `Antananarivo`,
    `Apia`,
    `Ashgabat`,
    `Asmara`,
    `Asuncion`,
    `Athens`,
    `Baghdad`,
    `Baku`,
    `Bamako`,
    `Bandar`,
    `Bangkok`,
]
/*
    `Bangui`,
    `Banjul`,
    `Basseterre`,
    `Beijing`,
    `Beirut`,
    `Belfast`,
    `Belgrade`,
    `Belmopan`,
    `Berlin`,
    `Bern`,
    `Bishkek`,
    `Bissau`,
    `Bogota`,
    `Brasilia`,
    `Bratislava`,
    `Brazzaville`,
    `Bridgetown`,
    `Brussels`,
    `Bucharest`,
    `Budapest`,
    `Buenos Aires`,
    `Cairo`,
    `Canberra`,
    `Caracas`,
    `Cardiff`,
    `Castries`,
    `Chisinau`,
    `Colombo`,
    `Conakry`,
    `Copenhagen`,
    `Dakar`,
    `Damascus`,
    `Dhaka`,
    `Dili`,
    `Djibouti`,
    `Dodoma`,
    `Doha`,
    `Dublin`,
    `Dushanbe`,
    `Edinburgh`,
    `Freetown`,
    `Funafuti`,
    `Gaborone`,
    `Georgetown`,
    `Gitega`,
    `Guatemala`,
    `Hanoi`,
    `Harare`,
    `Havana`,
    `Helsinki`,
    `Honiara`,
    `Islamabad`,
    `Jakarta`,
    `Jerusalem`,
    `Juba`,
    `Kabul`,
    `Kampala`,
    `Kathmandu`,
    `Khartoum`,
    `Kiev`,
    `Kigali`,
    `Kingston`,
    `Kingstown`,
    `Kinshasa`,
    `Kuala Lumpur`,
    `Kuwait`,
    `La Paz`,
    `Libreville`,
    `Lilongwe`,
    `Lima`,
    `Lisbon`,
    `Ljubljana`,
    `Lome`,
    `London`,
    `Luanda`,
    `Lusaka`,
    `Luxembourg`,
    `Madrid`,
    `Majuro`,
    `Malabo`,
    `Male`,
    `Managua`,
    `Manama`,
    `Manila`,
    `Maputo`,
    `Maseru`,
    `Mbabana`,
    `Melekeok`,
    `Mexico`,
    `Mexico City`,	
    `Minsk`,
    `Mogadishu`,
    `Monaco`,
    `Monrovia`,
    `Montevideo`,
    `Moroni`,
    `Moscow`,
    `Muscat`,
    `N'Djamena`,
    `Nairobi`,
    `Nassau`,
    `Nay Pyi Taw`,
    `New Delhi`,
    `Niamey`,
    `Nicosia`,
    `Nauru`,
    `Nouakchott`,
    `Nuku'alofa`,
    `Nur-Sultan`,
    `Oslo`,
    `Ottawa`,
    `Ouagadougou`,
    `Palikir`,
    `Panama City`,
    `Paramaribo`,
    `Paris`,
    `Phnom Penh`,
    `Podgorica`,
    `Port au Prince`,
    `Port Louis`,
    `Port Moresby`,
    `Port of Spain`,
    `Port Vila`,
    `Porto Novo`,
    `Prague`,
    `Praia`,
    `Pretoria`,
    `Pristina`,
    `Pyongyang`,
    `Quito`,
    `Rabat`,
    `Reykjavik`,
    `Riga`,
    `Riyadh`,
    `Rome`,
    `Roseau`,
    `Saint George's`,
    `Saint John's`,
    `San Jose`,
    `San Marino`,
    `San Salvador`,
    `Sana'a`,
    `Santiago`,
    `Santo Domingo`,
    `Sao Tome`,
    `Sarajevo`,
    `Seoul`,
    `Singapore`,
    `Skopje`,
    `Sofia`,
    `Stockholm`,
    `Suva`,
    `Taipei`,
    `Tallinn`,
    `Tarawa`,
    `Tashkent`,
    `Tbilisi`,
    `Tegucigalpa`,
    `Tehran`,
    `Thimphu`,
    `Tirana`,
    `Tokyo`,
    `Tripoli`,
    `Tunis`,
    `Ulaanbaatar`,
    `Vaduz`,
    `Valletta`,
    `Vatican`,
    `Victoria`,
    `Vienna`,
    `Vientiane`,
    `Vilnius`,
    `Warsaw`,
    `Washington D.C.`,
    `Wellington`,
    `Windhoek`,
    `Yamoussoukro`,
    `Yaounde`,
    `Yerevan`,
    `Zagreb`,
]
*/